/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author lucas
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();

        menuCadastroClientes.setText("Cadastro de Clientes");
        menuCadastroClientes.addActionListener(evt -> menu_AdcClienteActionPerformed(evt));
        menuCadastro.add(menuCadastroClientes);

        menuEditarClientes.setText("Editar Clientes");
        menuEditarClientes.addActionListener(evt -> menu_EdtClienteActionPerformed(evt));
        menuCadastro.add(menuEditarClientes);

        menuCadastroProdutos.setText("Cadastro de Produtos");
        menuCadastroProdutos.addActionListener(evt -> menu_AdcProdutoActionPerformed(evt));
        menuCadastro.add(menuCadastroProdutos);

        menuEditarProdutos.setText("Editar Produtos");
        menuEditarProdutos.addActionListener(evt -> menu_edtClienteActionPerformed(evt));
        menuCadastro.add(menuEditarProdutos);
        
        menuAdicionarNota.setText("Adicionar Nota");
        menuAdicionarNota.addActionListener(evt -> menu_AdcNotaActionPerformed(evt));
        menuCadastro.add(menuAdicionarNota);

        menuRelatorioClientes.setText("Relatório de Clientes");
        menuRelatorioClientes.addActionListener(evt -> menu_rltClienteActionPerformed(evt));
        menuRelatorios.add(menuRelatorioClientes);
        
        menuRelatorioProdutos.setText("Relatório de Produtos");
        menuRelatorioProdutos.addActionListener(evt -> menu_rltProdutoActionPerformed(evt));
        menuRelatorios.add(menuRelatorioProdutos);
        
        menuRelatorioNotas.setText("Relatório de Notas");
        menuRelatorioNotas.addActionListener(evt -> menu_rltNotaActionPerformed(evt));
        menuRelatorios.add(menuRelatorioNotas);

        menuSair.setText("Sair");
        menuSair.addActionListener(evt -> menuSairActionPerformed(evt));
        menuArquivo.add(menuSair);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarra = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroClientes = new javax.swing.JMenuItem();
        menuEditarClientes = new javax.swing.JMenuItem();
        menuCadastroProdutos = new javax.swing.JMenuItem();
        menuEditarProdutos = new javax.swing.JMenuItem();
        menuAdicionarNota = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuRelatorioClientes = new javax.swing.JMenuItem();
        menuRelatorioProdutos = new javax.swing.JMenuItem();
        menuRelatorioNotas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArquivo.setText("Arquivo");

        menuSair.setText("Sair");
        menuArquivo.add(menuSair);

        menuBarra.add(menuArquivo);

        menuCadastro.setText("Cadastro");

        menuCadastroClientes.setText("Cadastro de Clientes");
        menuCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroClientesActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroClientes);

        menuEditarClientes.setText("Editar Clientes");
        menuCadastro.add(menuEditarClientes);

        menuCadastroProdutos.setText("Cadastro de Produtos");
        menuCadastro.add(menuCadastroProdutos);

        menuEditarProdutos.setText("Editar Produtos");
        menuEditarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarProdutosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuEditarProdutos);

        menuAdicionarNota.setText("Adicionar Nota");
        menuCadastro.add(menuAdicionarNota);

        menuBarra.add(menuCadastro);

        menuRelatorios.setText("Relatórios");

        menuRelatorioClientes.setText("Relatorio de Clientes");
        menuRelatorios.add(menuRelatorioClientes);

        menuRelatorioProdutos.setText("Relatorio de Produtos");
        menuRelatorios.add(menuRelatorioProdutos);

        menuRelatorioNotas.setText("Relatorio de Notas");
        menuRelatorios.add(menuRelatorioNotas);

        menuBarra.add(menuRelatorios);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroClientesActionPerformed

    }//GEN-LAST:event_menuCadastroClientesActionPerformed

    private void menuEditarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEditarProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem menuAdicionarNota;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCadastroClientes;
    private javax.swing.JMenuItem menuCadastroProdutos;
    private javax.swing.JMenuItem menuEditarClientes;
    private javax.swing.JMenuItem menuEditarProdutos;
    private javax.swing.JMenuItem menuRelatorioClientes;
    private javax.swing.JMenuItem menuRelatorioNotas;
    private javax.swing.JMenuItem menuRelatorioProdutos;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuSair;
    // End of variables declaration//GEN-END:variables

    private void menu_AdcClienteActionPerformed(java.awt.event.ActionEvent evt) {
        AdicionarCliente adcCliente = new AdicionarCliente();
        adcCliente.setVisible(true);
    }

    private void menu_EdtClienteActionPerformed(java.awt.event.ActionEvent evt) {
        EditarCliente edtCliente = new EditarCliente();
        edtCliente.setVisible(true);
    }

    private void menu_AdcProdutoActionPerformed(java.awt.event.ActionEvent evt) {
        AdicionarProduto adcProduto = new AdicionarProduto();
        adcProduto.setVisible(true);
    }

    private void menu_edtClienteActionPerformed(java.awt.event.ActionEvent evt) {
        EditarExcluirProduto edtProduto = new EditarExcluirProduto();
        edtProduto.setVisible(true);
    }
    
    private void menu_AdcNotaActionPerformed(java.awt.event.ActionEvent evt) {
        AdicionarNota adcNota = new AdicionarNota();
        adcNota.setVisible(true);
    }

    private void menu_rltClienteActionPerformed(java.awt.event.ActionEvent evt) {
        RelatorioClientes rltClientes = new RelatorioClientes();
        rltClientes.setVisible(true);
    }
    
    private void menu_rltProdutoActionPerformed(java.awt.event.ActionEvent evt) {
        RelatorioProdutos rltProdutos = new RelatorioProdutos();
        rltProdutos.setVisible(true);
    }
    
    private void menu_rltNotaActionPerformed(java.awt.event.ActionEvent evt) {
        RelatorioNotas rltNotas = new RelatorioNotas();
        rltNotas.setVisible(true);
    }

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

}
